apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-2
  namespace: production-2
  labels:
    team: production
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "2Gi"
    limits.cpu: "2"
    limits.memory: "4Gi"
